version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /apps/client
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /apps/graphql
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    # Workflow files stored in the default location of `.github/workflows`
    directory: /
    schedule:
      interval: daily
