[build]
  command = "npm run build:netlify"
  functions = "apps"
  framework = "#static"
  publish = "apps/client/build"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
