import { LatLngTuple } from "leaflet";
import { v4 as uuidv4 } from "uuid";

export type dotsTree = {
  id: string;
  title: string;
  pinTreeId: string;
  isOpen: boolean;
  isSelected: boolean;
  detailsInfo: {
    treeId: string;
    speciesName: string;
    treeType: string;
    height: string;
    recordYear: number;
    owner: string;
    administrator: string;
  };
  treesListCoordinates: LatLngTuple;
};

export default [
  {
    id: uuidv4(),
    title: "Boom nummer 1",
    pinTreeId: "boom 1",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.378158, 4.84652],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 2",
    pinTreeId: "boom 1",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.378102, 4.84615],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 3",
    pinTreeId: "boom 1",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.377933, 4.846711],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 4",
    pinTreeId: "boom 1",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.377866, 4.846322],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 5",
    pinTreeId: "boom 1",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.377997, 4.845759],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 6",
    pinTreeId: "boom 1",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.377742, 4.845783],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 7",
    pinTreeId: "boom 1",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.377684, 4.845524],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 8",
    pinTreeId: "boom 1",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.377859, 4.845406],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 9",
    pinTreeId: "boom 1",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.377896, 4.84508],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 10",
    pinTreeId: "boom 1",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.377675, 4.845014],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 11",
    pinTreeId: "boom 2",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.381187, 4.872907],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 12",
    pinTreeId: "boom 2",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.381226, 4.873103],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 13",
    pinTreeId: "boom 2",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.381139, 4.873189],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 14",
    pinTreeId: "boom 2",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.381141, 4.873264],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 15",
    pinTreeId: "boom 2",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.38108, 4.873339],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 16",
    pinTreeId: "boom 2",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.38102, 4.87336],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 17",
    pinTreeId: "boom 2",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.380963, 4.873472],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 18",
    pinTreeId: "boom 2",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.381035, 4.873471],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 19",
    pinTreeId: "boom 2",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.381073, 4.873482],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 20",
    pinTreeId: "boom 2",
    isOpen: false,
    isSelected: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    treesListCoordinates: [52.381084, 4.873506],
  },
];
