import { v4 as uuidv4 } from "uuid";

export default [
  {
    id: uuidv4(),
    title: "Boom nummer 1",
    isOpen: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
  },
  {
    id: uuidv4(),
    title: "Boom nummer 2",
    isOpen: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
  },
  {
    id: uuidv4(),
    title: "Boom nummer 3",
    isOpen: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
  },
  {
    id: uuidv4(),
    title: "Boom nummer 4",
    isOpen: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
  },
  {
    id: uuidv4(),
    title: "Boom nummer 5",
    isOpen: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
    coordinatesTreesList: [
      [52.381329, 4.873074],
      [52.381491, 4.873006],
      [52.381406, 4.87305],
    ],
  },
  {
    id: uuidv4(),
    title: "Boom nummer 6",
    isOpen: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
  },
  {
    id: uuidv4(),
    title: "Boom nummer 7",
    isOpen: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
  },
  {
    id: uuidv4(),
    title: "Boom nummer 8",
    isOpen: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
  },
  {
    id: uuidv4(),
    title: "Boom nummer 9",
    isOpen: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
  },
  {
    id: uuidv4(),
    title: "Boom nummer 10",
    isOpen: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
  },
  {
    id: uuidv4(),
    title: "Boom nummer 11",
    isOpen: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
  },
  {
    id: uuidv4(),
    title: "Boom nummer 12",
    isOpen: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
  },
  {
    id: uuidv4(),
    title: "Boom nummer 13",
    isOpen: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
  },
  {
    id: uuidv4(),
    title: "Boom nummer 14",
    isOpen: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
  },
  {
    id: uuidv4(),
    title: "Boom nummer 15",
    isOpen: false,
    detailsInfo: {
      treeId: "344594",
      speciesName: "Ulmus hollandica",
      treeType: "Boom vrij uitgroeiend",
      height: "12 tot 15m.",
      recordYear: 1950,
      owner: "Gemeente Amsterdam",
      administrator: "Stadsdeel Centrum",
    },
  },
];
