FROM node:alpine AS builder
LABEL maintainer="datapunt@amsterdam.nl"

WORKDIR /app/
COPY apps/graphql/package*.json ./
RUN npm ci --no-color -q
COPY apps/graphql/ .

# Test, disabled because of redis requirement
# FROM builder
# RUN npm test

# Release

# Enable when Node docker image is done
FROM amsterdam/node
WORKDIR /app/

COPY --from=builder /app/ /app/

USER node
ENV NODE_OPTIONS=--use-openssl-ca
ENV PORT=8080
ENV NODE_ENV=production
CMD node .
