FROM node:alpine
WORKDIR /app/

# Install
COPY . ./

RUN rm -rf packages/client packages/graphql packages/imtr-client

# Test
RUN npm i
RUN cd packages/e2e/ && CI=true npm run nightwatch:browserstack
