FROM node:alpine AS builder
LABEL maintainer="datapunt@amsterdam.nl"

WORKDIR /app/
COPY apps/graphql/package*.json ./
RUN npm ci --no-color -q
COPY apps/graphql/ .

# Test, disabled because of redis requirement
# FROM builder
# RUN npm test

# Release
FROM builder
ARG NODE_ENV
USER node
ENV PORT=8080
CMD node .
