FROM hayd/alpine-deno
WORKDIR /app/

# Install node / npm
RUN apk add --update npm

# Install
COPY . ./

# Setup non-root user
RUN addgroup -S devs
RUN adduser -S -G devs dev
RUN chown -R dev:devs /app/ /deno-dir/
RUN chmod +s /app/ /deno-dir/
USER dev:devs

# Install
RUN npm i
RUN npm run imtr
