name: Github CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches: "*"

jobs:
  build:
    strategy:
      matrix:
        node-version: [14]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

      # Start running the test coverage action
      - run: npm run test:coverage
      - name: Running code coverage
        uses: codecov/codecov-action@v1.5.2

      # @TODO: enable e2e tests here
      # run: CI=true npm run test (e2e test)

      # @TODO: Build custom size diff calculator because this gives us too many unclear comments
      # Start running the calculation of the bundle size action
      # - name: Calculating size
      #   if: ${{ github.event_name == 'pull_request'}} # Only calculate size on PRs
      #   uses: chrysanthos/simple-asset-size-reporter@1.0.2
      #   with:
      #     repo-token: "${{ secrets.GITHUB_TOKEN }}"
      #     files: '["packages/client/build/static/js/*.js", "packages/client/build/static/css/*.css"]'
      #     with-same: "false"
      #     build-assets: "npm run build:size-report"
