name: Simple Asset Size Reporter

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: cd apps/client && npm install
      - name: Calculating size
        uses: chrysanthos/simple-asset-size-reporter@1.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          files: '["apps/client/*.js", "public/css/*.css"]'
          with-same: "false"
          build-assets: "cd apps/client && npm run build"
