name: Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Calculating build size
        uses: preactjs/compressed-size-action@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          build-script: "start:calculate-size"
