name: Simple Size Reporter

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Calculating size
        uses: chrysanthos/simple-asset-size-reporter@1.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          files: '["apps/client/build/static/js/*.js", "apps/client/build/static/css/*.css"]'
          with-same: "false"
          build-assets: "npm run build:size-report"
