# Generated by Django 3.1.3 on 2021-02-04 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0002_auto_20201109_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('imtr_url', models.CharField(default='', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='permit_ids',
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
