# Generated by Django 3.1.3 on 2021-02-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0003_auto_20210204_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chappie.topic'),
        ),
    ]
