# Generated by Django 3.1.3 on 2021-02-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0004_permit_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='heading',
            field=models.CharField(default='', max_length=80),
        ),
    ]
