# Generated by Django 3.1.3 on 2021-04-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0005_topic_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permit',
            name='imtr_url',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='url',
        ),
        migrations.AddField(
            model_name='permit',
            name='flo_legal_id',
            field=models.CharField(default='', help_text="Dit is het id uit de url in de FloLegal STTR Builder. Bijvoorbeeld 'WKPxKx4YBJ5fqYSni' uit 'https://sttr-builder.flolegal.app/#/activiteit/WKPxKx4YBJ5fqYSni'", max_length=200),
        ),
    ]
