# Generated by Django 3.1.3 on 2021-04-12 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0009_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chappie.topic'),
        ),
    ]
