# Generated by Django 3.1.3 on 2021-04-12 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0011_auto_20210412_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outcome',
            old_name='intro',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='outcome',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='chappie.topic'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='chappie.topic'),
        ),
    ]
