# Generated by Django 3.1.3 on 2021-04-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0012_auto_20210412_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='flow',
            field=models.IntegerField(choices=[('IMTR', 'IMTR'), ('OLO', 'OLO'), ('REDIRECT_TO_OLO', 'REDIRECT_TO_OLO')]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
