# Generated by Django 3.1.3 on 2021-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0013_auto_20210412_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='flow',
            field=models.CharField(choices=[('IMTR', 'IMTR'), ('OLO', 'OLO'), ('REDIRECT_TO_OLO', 'REDIRECT_TO_OLO')], max_length=30),
        ),
    ]
