# Generated by Django 3.2.3 on 2021-05-24 10:11

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0014_auto_20210412_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outcome',
            options={'verbose_name': 'Uitkomst', 'verbose_name_plural': 'Uitkomsten'},
        ),
        migrations.AlterModelOptions(
            name='permit',
            options={'verbose_name': 'Vergunning', 'verbose_name_plural': 'Vergunningen'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Checker'},
        ),
        migrations.RemoveField(
            model_name='permit',
            name='topic',
        ),
        migrations.AddField(
            model_name='topic',
            name='permits',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='chappie.Permit'),
        ),
    ]
