# Generated by Django 3.2.4 on 2021-06-04 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0015_auto_20210524_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMTRConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('version', models.IntegerField()),
                ('blob', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='permit',
            name='imtr_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chappie.imtrconfig'),
        ),
    ]
