# Generated by Django 3.2.4 on 2021-06-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0016_auto_20210604_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='imtr_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chappie.imtrconfig'),
        ),
    ]
