# Generated by Django 3.2.4 on 2021-06-30 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0018_auto_20210623_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='imtrconfig',
            name='config_permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chappie.permit'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='chappie.topic', verbose_name='Checker'),
        ),
    ]
