# Generated by Django 3.2.4 on 2021-06-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0020_alter_topic_location_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='location_intro',
        ),
        migrations.AlterField(
            model_name='topic',
            name='flow',
            field=models.CharField(choices=[('IMTR', 'IMTR'), ('OLO', 'OLO'), ('REDIRECT_TO_OLO', 'REDIRECT_TO_OLO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user_might_not_need_permit',
            field=models.BooleanField(default=True, help_text="Enables an add-on text in the QuestionAlert: 'If you make another choice you might not need a permit.'"),
        ),
        migrations.AddField(
            model_name='topic',
            name='pre_questions',
            field=models.ManyToManyField(to='chappie.PreQuestions'),
        ),
    ]
