# Generated by Django 3.2.4 on 2021-06-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0021_auto_20210630_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreQuestions',
            new_name='PreQuestion',
        ),
    ]
