# Generated by Django 3.2.4 on 2021-06-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0024_auto_20210630_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='pre_questions',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='chappie.PreQuestion'),
        ),
    ]
