# Generated by Django 3.2.4 on 2021-07-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0025_alter_topic_pre_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='flow',
            field=models.CharField(choices=[('IMTR', 'IMTR'), ('OLO', 'OLO')], max_length=20),
        ),
    ]
