# Generated by Django 3.2.4 on 2021-07-02 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chappie', '0026_auto_20210702_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imtrconfig',
            options={'verbose_name': 'IMTR configuratie', 'verbose_name_plural': 'IMTR configuraties'},
        ),
        migrations.AlterModelOptions(
            name='prequestion',
            options={'verbose_name': 'Vraag vooraf', 'verbose_name_plural': 'Vragen vooraf'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Vergunningcheck', 'verbose_name_plural': 'Vergunningchecks'},
        ),
        migrations.AlterField(
            model_name='imtrconfig',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
